### ISSUE TITLE
EKS Support

### ISSUE THREAD

**Issue by marcwickenden** [4ARMED/kubeletmein#1]
Add support for Amazon EKS.

**Comment by RichardoC** [comment]
If you have the [aws-cli](https://github.com/aws/aws-cli) installed, it's as simple as the following to do the same for EKS

```shell
export ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)

export AWS_DEFAULT_REGION=$(echo $ZONE | awk '{print substr($0, 1, length($0)-1)}')

aws eks update-kubeconfig --name $CLUSTER-NAME
```

This was butchered from the node [bootstrap.sh ](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) script

**Comment by marcwickenden** [comment]
Indeed it is this simple, thank you for including the instructions. My plan was to utilise the Heptio IAM authenticator, vendor that in and call out from that. I have a feeling AWS have changed the way that works now though but fundamentally it is still just a case of grabbing IAM creds for the node and off you go.

**Comment by RichardoC** [comment]
Sounds good, you might also be able to do the same via the aws golang sdk?

**Comment by mcruz-gh** [comment]
Unfortunately, this is not a simple issue. First of all, you need to take a set of secret and access keys from instance metadata. That could be easy, but the k8s token (issued to username: system:node:{EC2PrivateDNSName}) obtained using that set of keys with iam-authenticator does not have the required privileges to execute actions like create or modify cluster objects (like configmaps), or even try some sort of privilege escalation. That is because Node Authorization is set up in the Master Node.
